services:
  react:
    build:
      target: dev
    ports:
      - "${PORT:-8888}"
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    env_file:
      - .env.dev

volumes:
  node_modules:
